// Mocks generated by Mockito from annotations
// in launcher_icons/test/macos/macos_icon_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:cli_util/cli_logging.dart' as _i2;
import 'package:launcher_icons/src/config/config.dart' as _i3;
import 'package:launcher_icons/src/config/macos_config.dart' as _i4;
import 'package:launcher_icons/src/core/logger.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProgress_1 extends _i1.SmartFake implements _i2.Progress {
  _FakeProgress_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i3.Config {
  @override
  bool get svgRasterizePerSize => (super.noSuchMethod(
        Invocation.getter(#svgRasterizePerSize),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasAndroidAdaptiveConfig => (super.noSuchMethod(
        Invocation.getter(#hasAndroidAdaptiveConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasAndroidAdaptiveMonochromeConfig => (super.noSuchMethod(
        Invocation.getter(#hasAndroidAdaptiveMonochromeConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasAndroidAdaptiveRoundConfig => (super.noSuchMethod(
        Invocation.getter(#hasAndroidAdaptiveRoundConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasEnabledPlatform => (super.noSuchMethod(
        Invocation.getter(#hasEnabledPlatform),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasAndroidConfig => (super.noSuchMethod(
        Invocation.getter(#hasAndroidConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasIOSConfig => (super.noSuchMethod(
        Invocation.getter(#hasIOSConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasWebConfig => (super.noSuchMethod(
        Invocation.getter(#hasWebConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasWindowsConfig => (super.noSuchMethod(
        Invocation.getter(#hasWindowsConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMacOSConfig => (super.noSuchMethod(
        Invocation.getter(#hasMacOSConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasLinuxConfig => (super.noSuchMethod(
        Invocation.getter(#hasLinuxConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isCustomAndroidFile => (super.noSuchMethod(
        Invocation.getter(#isCustomAndroidFile),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNeedingNewAndroidIcon => (super.noSuchMethod(
        Invocation.getter(#isNeedingNewAndroidIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNeedingNewIOSIcon => (super.noSuchMethod(
        Invocation.getter(#isNeedingNewIOSIcon),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasLiquidGlassIconConfig => (super.noSuchMethod(
        Invocation.getter(#hasLiquidGlassIconConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasMacOSLiquidGlassIconConfig => (super.noSuchMethod(
        Invocation.getter(#hasMacOSLiquidGlassIconConfig),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [MacOSConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockMacOSConfig extends _i1.Mock implements _i4.MacOSConfig {
  @override
  bool get generate => (super.noSuchMethod(
        Invocation.getter(#generate),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get padding => (super.noSuchMethod(
        Invocation.getter(#padding),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get roundedCorners => (super.noSuchMethod(
        Invocation.getter(#roundedCorners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get removeLiquidGlass => (super.noSuchMethod(
        Invocation.getter(#removeLiquidGlass),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get backgroundColor => (super.noSuchMethod(
        Invocation.getter(#backgroundColor),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#backgroundColor),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#backgroundColor),
        ),
      ) as String);

  @override
  bool get liquidGlassSpecular => (super.noSuchMethod(
        Invocation.getter(#liquidGlassSpecular),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get liquidGlassShadowKind => (super.noSuchMethod(
        Invocation.getter(#liquidGlassShadowKind),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#liquidGlassShadowKind),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#liquidGlassShadowKind),
        ),
      ) as String);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [LILogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLILogger extends _i1.Mock implements _i6.LILogger {
  @override
  bool get isVerbose => (super.noSuchMethod(
        Invocation.getter(#isVerbose),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Logger get rawLogger => (super.noSuchMethod(
        Invocation.getter(#rawLogger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#rawLogger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#rawLogger),
        ),
      ) as _i2.Logger);

  @override
  void error(Object? message) => super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void verbose(Object? message) => super.noSuchMethod(
        Invocation.method(
          #verbose,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(Object? message) => super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Progress progress(String? message) => (super.noSuchMethod(
        Invocation.method(
          #progress,
          [message],
        ),
        returnValue: _FakeProgress_1(
          this,
          Invocation.method(
            #progress,
            [message],
          ),
        ),
        returnValueForMissingStub: _FakeProgress_1(
          this,
          Invocation.method(
            #progress,
            [message],
          ),
        ),
      ) as _i2.Progress);
}
