// Mocks generated by Mockito from annotations
// in launcher_icons/test/abs/icon_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:launcher_icons/src/config/config.dart' as _i3;
import 'package:launcher_icons/src/core/icon_generator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIconGeneratorContext_0 extends _i1.SmartFake
    implements _i2.IconGeneratorContext {
  _FakeIconGeneratorContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i3.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get androidEnabled => (super.noSuchMethod(
        Invocation.getter(#androidEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get iosEnabled => (super.noSuchMethod(
        Invocation.getter(#iosEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get webEnabled => (super.noSuchMethod(
        Invocation.getter(#webEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get windowsEnabled => (super.noSuchMethod(
        Invocation.getter(#windowsEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get macOSEnabled => (super.noSuchMethod(
        Invocation.getter(#macOSEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get linuxEnabled => (super.noSuchMethod(
        Invocation.getter(#linuxEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasEnabledPlatform => (super.noSuchMethod(
        Invocation.getter(#hasEnabledPlatform),
        returnValue: false,
      ) as bool);

  @override
  String resolveImageFile(
    String? platformImagePath,
    String? prefixPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveImageFile,
          [
            platformImagePath,
            prefixPath,
          ],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #resolveImageFile,
            [
              platformImagePath,
              prefixPath,
            ],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [IconGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIconGenerator extends _i1.Mock implements _i2.IconGenerator {
  MockIconGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IconGeneratorContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeIconGeneratorContext_0(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.IconGeneratorContext);

  @override
  String get platformName => (super.noSuchMethod(
        Invocation.getter(#platformName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#platformName),
        ),
      ) as String);

  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> createIcons() => (super.noSuchMethod(
        Invocation.method(
          #createIcons,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool validateRequirements() => (super.noSuchMethod(
        Invocation.method(
          #validateRequirements,
          [],
        ),
        returnValue: false,
      ) as bool);
}
